# Generated by Django 2.1.9 on 2019-07-10 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('pages', '0002_auto_20190710_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(max_length=120)),
                ('manager', models.BooleanField(default=False)),
            ],
        ),
    ]
