# Generated by Django 2.1.9 on 2019-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=50)),
                ('tower', models.CharField(max_length=50)),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
    ]
