# Generated by Django 2.1.9 on 2019-07-10 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Rating')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Skills')),
            ],
        ),
    ]
